package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

/**
 * Detailworking generated by hbm2java
 */
public class Detailworking implements java.io.Serializable {

	private DetailworkingId id;
	private Staff staff;
	private Workingtime workingtime;
	private Registerleave registerleave;

	public Detailworking() {
	}

	public Detailworking(DetailworkingId id) {
		this.id = id;
	}

	public Detailworking(DetailworkingId id, Staff staff, Workingtime workingtime, Registerleave registerleave) {
		this.id = id;
		this.staff = staff;
		this.workingtime = workingtime;
		this.registerleave = registerleave;
	}

	public DetailworkingId getId() {
		return this.id;
	}

	public void setId(DetailworkingId id) {
		this.id = id;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Workingtime getWorkingtime() {
		return this.workingtime;
	}

	public void setWorkingtime(Workingtime workingtime) {
		this.workingtime = workingtime;
	}

	public Registerleave getRegisterleave() {
		return this.registerleave;
	}

	public void setRegisterleave(Registerleave registerleave) {
		this.registerleave = registerleave;
	}

}
