package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Detailorder generated by hbm2java
 */
public class Detailorder implements java.io.Serializable {

	private int id;
	private Ftable ftable;
	private Staff staff;
	private Food food;
	private Integer numberofcustomer;
	private Date startdate;

	public Detailorder() {
	}

	public Detailorder(int id, Ftable ftable, Staff staff, Food food, Date startdate) {
		this.id = id;
		this.ftable = ftable;
		this.staff = staff;
		this.food = food;
		this.startdate = startdate;
	}

	public Detailorder(int id, Ftable ftable, Staff staff, Food food, Integer numberofcustomer, Date startdate) {
		this.id = id;
		this.ftable = ftable;
		this.staff = staff;
		this.food = food;
		this.numberofcustomer = numberofcustomer;
		this.startdate = startdate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ftable getFtable() {
		return this.ftable;
	}

	public void setFtable(Ftable ftable) {
		this.ftable = ftable;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Food getFood() {
		return this.food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	public Integer getNumberofcustomer() {
		return this.numberofcustomer;
	}

	public void setNumberofcustomer(Integer numberofcustomer) {
		this.numberofcustomer = numberofcustomer;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

}
