package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * DetailworkingId generated by hbm2java
 */
public class DetailworkingId implements java.io.Serializable {

	private Integer idStaff;
	private Integer idWorkingtime;
	private Date workingdate;
	private Integer idRegisterleave;

	public DetailworkingId() {
	}

	public DetailworkingId(Date workingdate) {
		this.workingdate = workingdate;
	}

	public DetailworkingId(Integer idStaff, Integer idWorkingtime, Date workingdate, Integer idRegisterleave) {
		this.idStaff = idStaff;
		this.idWorkingtime = idWorkingtime;
		this.workingdate = workingdate;
		this.idRegisterleave = idRegisterleave;
	}

	public Integer getIdStaff() {
		return this.idStaff;
	}

	public void setIdStaff(Integer idStaff) {
		this.idStaff = idStaff;
	}

	public Integer getIdWorkingtime() {
		return this.idWorkingtime;
	}

	public void setIdWorkingtime(Integer idWorkingtime) {
		this.idWorkingtime = idWorkingtime;
	}

	public Date getWorkingdate() {
		return this.workingdate;
	}

	public void setWorkingdate(Date workingdate) {
		this.workingdate = workingdate;
	}

	public Integer getIdRegisterleave() {
		return this.idRegisterleave;
	}

	public void setIdRegisterleave(Integer idRegisterleave) {
		this.idRegisterleave = idRegisterleave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailworkingId))
			return false;
		DetailworkingId castOther = (DetailworkingId) other;

		return ((this.getIdStaff() == castOther.getIdStaff()) || (this.getIdStaff() != null
				&& castOther.getIdStaff() != null && this.getIdStaff().equals(castOther.getIdStaff())))
				&& ((this.getIdWorkingtime() == castOther.getIdWorkingtime())
						|| (this.getIdWorkingtime() != null && castOther.getIdWorkingtime() != null
								&& this.getIdWorkingtime().equals(castOther.getIdWorkingtime())))
				&& ((this.getWorkingdate() == castOther.getWorkingdate())
						|| (this.getWorkingdate() != null && castOther.getWorkingdate() != null
								&& this.getWorkingdate().equals(castOther.getWorkingdate())))
				&& ((this.getIdRegisterleave() == castOther.getIdRegisterleave())
						|| (this.getIdRegisterleave() != null && castOther.getIdRegisterleave() != null
								&& this.getIdRegisterleave().equals(castOther.getIdRegisterleave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdStaff() == null ? 0 : this.getIdStaff().hashCode());
		result = 37 * result + (getIdWorkingtime() == null ? 0 : this.getIdWorkingtime().hashCode());
		result = 37 * result + (getWorkingdate() == null ? 0 : this.getWorkingdate().hashCode());
		result = 37 * result + (getIdRegisterleave() == null ? 0 : this.getIdRegisterleave().hashCode());
		return result;
	}

}
