package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Food generated by hbm2java
 */
public class Food implements java.io.Serializable {

	private int id;
	private String name;
	private Double price;
	private String note;
	private Set<Detailorder> detailorders = new HashSet<Detailorder>(0);

	public Food() {
	}

	public Food(int id) {
		this.id = id;
	}

	public Food(int id, String name, Double price, String note, Set<Detailorder> detailorders) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.note = note;
		this.detailorders = detailorders;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<Detailorder> getDetailorders() {
		return this.detailorders;
	}

	public void setDetailorders(Set<Detailorder> detailorders) {
		this.detailorders = detailorders;
	}

}
