package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ftable generated by hbm2java
 */
public class Ftable implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Detailorder> detailorders = new HashSet<Detailorder>(0);

	public Ftable() {
	}

	public Ftable(int id) {
		this.id = id;
	}

	public Ftable(int id, String name, Set<Detailorder> detailorders) {
		this.id = id;
		this.name = name;
		this.detailorders = detailorders;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Detailorder> getDetailorders() {
		return this.detailorders;
	}

	public void setDetailorders(Set<Detailorder> detailorders) {
		this.detailorders = detailorders;
	}

}
