package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registerleave generated by hbm2java
 */
public class Registerleave implements java.io.Serializable {

	private int id;
	private Staff staff;
	private Registerstatus registerstatus;
	private Workingtime workingtime;
	private Date leavedate;
	private Set<Detailworking> detailworkings = new HashSet<Detailworking>(0);

	public Registerleave() {
	}

	public Registerleave(int id, Date leavedate) {
		this.id = id;
		this.leavedate = leavedate;
	}

	public Registerleave(int id, Staff staff, Registerstatus registerstatus, Workingtime workingtime, Date leavedate,
			Set<Detailworking> detailworkings) {
		this.id = id;
		this.staff = staff;
		this.registerstatus = registerstatus;
		this.workingtime = workingtime;
		this.leavedate = leavedate;
		this.detailworkings = detailworkings;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Registerstatus getRegisterstatus() {
		return this.registerstatus;
	}

	public void setRegisterstatus(Registerstatus registerstatus) {
		this.registerstatus = registerstatus;
	}

	public Workingtime getWorkingtime() {
		return this.workingtime;
	}

	public void setWorkingtime(Workingtime workingtime) {
		this.workingtime = workingtime;
	}

	public Date getLeavedate() {
		return this.leavedate;
	}

	public void setLeavedate(Date leavedate) {
		this.leavedate = leavedate;
	}

	public Set<Detailworking> getDetailworkings() {
		return this.detailworkings;
	}

	public void setDetailworkings(Set<Detailworking> detailworkings) {
		this.detailworkings = detailworkings;
	}

}
