package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private int id;
	private Typestaff typestaff;
	private String fullname;
	private String address;
	private String accName;
	private String email;
	private String password;
	private Boolean sex;
	private Date birthday;
	private Set<Registerleave> registerleaves = new HashSet<Registerleave>(0);
	private Set<Detailorder> detailorders = new HashSet<Detailorder>(0);
	private Set<Detailworking> detailworkings = new HashSet<Detailworking>(0);

	public Staff() {
	}

	public Staff(int id, Typestaff typestaff) {
		this.id = id;
		this.typestaff = typestaff;
	}

	public Staff(int id, Typestaff typestaff, String fullname, String address, String accName, String email,
			String password, Boolean sex, Date birthday, Set<Registerleave> registerleaves,
			Set<Detailorder> detailorders, Set<Detailworking> detailworkings) {
		this.id = id;
		this.typestaff = typestaff;
		this.fullname = fullname;
		this.address = address;
		this.accName = accName;
		this.email = email;
		this.password = password;
		this.sex = sex;
		this.birthday = birthday;
		this.registerleaves = registerleaves;
		this.detailorders = detailorders;
		this.detailworkings = detailworkings;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Typestaff getTypestaff() {
		return this.typestaff;
	}

	public void setTypestaff(Typestaff typestaff) {
		this.typestaff = typestaff;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Set<Registerleave> getRegisterleaves() {
		return this.registerleaves;
	}

	public void setRegisterleaves(Set<Registerleave> registerleaves) {
		this.registerleaves = registerleaves;
	}

	public Set<Detailorder> getDetailorders() {
		return this.detailorders;
	}

	public void setDetailorders(Set<Detailorder> detailorders) {
		this.detailorders = detailorders;
	}

	public Set<Detailworking> getDetailworkings() {
		return this.detailworkings;
	}

	public void setDetailworkings(Set<Detailworking> detailworkings) {
		this.detailworkings = detailworkings;
	}

}
