package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Typestaff generated by hbm2java
 */
public class Typestaff implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public Typestaff() {
	}

	public Typestaff(int id) {
		this.id = id;
	}

	public Typestaff(int id, String name, Set<Staff> staffs) {
		this.id = id;
		this.name = name;
		this.staffs = staffs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

}
