package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Workingtime generated by hbm2java
 */
public class Workingtime implements java.io.Serializable {

	private int id;
	private Integer starthour;
	private Integer endhour;
	private Set<Detailworking> detailworkings = new HashSet<Detailworking>(0);
	private Set<Registerleave> registerleaves = new HashSet<Registerleave>(0);

	public Workingtime() {
	}

	public Workingtime(int id) {
		this.id = id;
	}

	public Workingtime(int id, Integer starthour, Integer endhour, Set<Detailworking> detailworkings,
			Set<Registerleave> registerleaves) {
		this.id = id;
		this.starthour = starthour;
		this.endhour = endhour;
		this.detailworkings = detailworkings;
		this.registerleaves = registerleaves;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getStarthour() {
		return this.starthour;
	}

	public void setStarthour(Integer starthour) {
		this.starthour = starthour;
	}

	public Integer getEndhour() {
		return this.endhour;
	}

	public void setEndhour(Integer endhour) {
		this.endhour = endhour;
	}

	public Set<Detailworking> getDetailworkings() {
		return this.detailworkings;
	}

	public void setDetailworkings(Set<Detailworking> detailworkings) {
		this.detailworkings = detailworkings;
	}

	public Set<Registerleave> getRegisterleaves() {
		return this.registerleaves;
	}

	public void setRegisterleaves(Set<Registerleave> registerleaves) {
		this.registerleaves = registerleaves;
	}

}
