package hcmus.maven.pojo;
// Generated Jun 13, 2016 2:22:39 PM by Hibernate Tools 3.5.0.Final

/**
 * Workingstatus generated by hbm2java
 */
public class Workingstatus implements java.io.Serializable {

	private int id;
	private String name;

	public Workingstatus() {
	}

	public Workingstatus(int id) {
		this.id = id;
	}

	public Workingstatus(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
